// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pickleball_Smash.Data;

#nullable disable

namespace Pickleball_Smash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pickleball_Smash.Models.ChiNhanh", b =>
                {
                    b.Property<int>("ChiNhanhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiNhanhID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT_LienHe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChiNhanhID");

                    b.ToTable("CHI_NHANH", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("ChiTietDichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDichVuID"));

                    b.Property<int?>("DichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("DichVuPhuTroDichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ChiTietDichVuID");

                    b.HasIndex("DichVuPhuTroDichVuID");

                    b.HasIndex("DonDatSanID");

                    b.ToTable("CHI_TIET_DICH_VU", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaID"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<int?>("SanPickleballSanID")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanPickleballSanID");

                    b.ToTable("DANH_GIA", null, t =>
                        {
                            t.HasCheckConstraint("CK_DANH_GIA_SoSao", "SoSao >= 1 AND SoSao <= 5");
                        });
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DichVuPhuTro", b =>
                {
                    b.Property<int>("DichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuID"));

                    b.Property<decimal?>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DichVuID");

                    b.ToTable("DICH_VU_PHU_TRO", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.Property<int>("DonDatSanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonDatSanID"));

                    b.Property<DateOnly>("NgayChoi")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<int?>("SanPickleballSanID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonDatSanID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanPickleballSanID");

                    b.ToTable("DON_DAT_SAN", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.LichSuChat", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatID"));

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("LICH_SU_CHAT", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.SanPickleball", b =>
                {
                    b.Property<int>("SanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanID"));

                    b.Property<int>("ChiNhanhID")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("SanID");

                    b.HasIndex("ChiNhanhID");

                    b.HasIndex("TenSan", "ChiNhanhID")
                        .IsUnique();

                    b.ToTable("SAN_PICKLEBALL", null, t =>
                        {
                            t.HasCheckConstraint("CK_SAN_PICKLEBALL_GiaCoBan", "GiaCoBan >= 0");

                            t.HasCheckConstraint("CK_SAN_PICKLEBALL_LoaiSan", "LoaiSan IN (N'Trong nhà', N'Ngoài trời')");

                            t.HasCheckConstraint("CK_SAN_PICKLEBALL_TrangThai", "TrangThai IN (N'Mở', N'Đóng')");
                        });
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanID"));

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThanhToanID");

                    b.HasIndex("DonDatSanID");

                    b.ToTable("THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.DichVuPhuTro", "DichVuPhuTro")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DichVuPhuTroDichVuID");

                    b.HasOne("Pickleball_Smash.Models.DonDatSan", "DonDatSan")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DonDatSanID");

                    b.Navigation("DichVuPhuTro");

                    b.Navigation("DonDatSan");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DanhGia", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPickleballSanID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonDatSans")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smash.Models.SanPickleball", "SanPickleball")
                        .WithMany("DonDatSans")
                        .HasForeignKey("SanPickleballSanID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.LichSuChat", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuChats")
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.SanPickleball", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("SanPickleballs")
                        .HasForeignKey("ChiNhanhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ThanhToan", b =>
                {
                    b.HasOne("Pickleball_Smash.Models.DonDatSan", "DonDatSan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DonDatSanID");

                    b.Navigation("DonDatSan");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.ChiNhanh", b =>
                {
                    b.Navigation("SanPickleballs");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DichVuPhuTro", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.DonDatSan", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");

                    b.Navigation("LichSuChats");
                });

            modelBuilder.Entity("Pickleball_Smash.Models.SanPickleball", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");
                });
#pragma warning restore 612, 618
        }
    }
}
