// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pickleball_Smart.Data;

#nullable disable

namespace Pickleball_Smart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302082848_TaoCoSoDuLieuBanDau")]
    partial class TaoCoSoDuLieuBanDau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pickleball_Smart.Models.ChiNhanh", b =>
                {
                    b.Property<int>("ChiNhanhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiNhanhID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT_LienHe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChiNhanhID");

                    b.ToTable("ChiNhanh", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("ChiTietDichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDichVuID"));

                    b.Property<int?>("DichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("DichVuPhuTroDichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ChiTietDichVuID");

                    b.HasIndex("DichVuPhuTroDichVuID");

                    b.HasIndex("DonDatSanID");

                    b.ToTable("ChiTietDichVu", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaID"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<int?>("SanPickleballSanID")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanPickleballSanID");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DichVuPhuTro", b =>
                {
                    b.Property<int>("DichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuID"));

                    b.Property<decimal?>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DichVuID");

                    b.ToTable("DichVuPhuTro", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DonDatSan", b =>
                {
                    b.Property<int>("DonDatSanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonDatSanID"));

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayChoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("SanID")
                        .HasColumnType("int");

                    b.Property<int?>("SanPickleballSanID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonDatSanID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("SanPickleballSanID");

                    b.ToTable("DonDatSan", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.GhepCapAI", b =>
                {
                    b.Property<int>("GhepCapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GhepCapID"));

                    b.Property<string>("KieuGhep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GhepCapID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("GhepCapAI", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.LichSuChat", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatID"));

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("LichSuChat", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.SanPickleball", b =>
                {
                    b.Property<int>("SanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanID"));

                    b.Property<int?>("ChiNhanhID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SanID");

                    b.HasIndex("ChiNhanhID");

                    b.HasIndex("TenSan", "ChiNhanhID")
                        .IsUnique()
                        .HasFilter("[ChiNhanhID] IS NOT NULL");

                    b.ToTable("SanPickleball", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanID"));

                    b.Property<int?>("DonDatSanID")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThanhToanID");

                    b.HasIndex("DonDatSanID");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Pickleball_Smart.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.DichVuPhuTro", "DichVuPhuTro")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DichVuPhuTroDichVuID");

                    b.HasOne("Pickleball_Smart.Models.DonDatSan", "DonDatSan")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DonDatSanID");

                    b.Navigation("DichVuPhuTro");

                    b.Navigation("DonDatSan");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DanhGia", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smart.Models.SanPickleball", "SanPickleball")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPickleballSanID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DonDatSan", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonDatSans")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Pickleball_Smart.Models.SanPickleball", "SanPickleball")
                        .WithMany("DonDatSans")
                        .HasForeignKey("SanPickleballSanID");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPickleball");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.GhepCapAI", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.NguoiDung", "NguoiDung")
                        .WithMany("GhepCapAIs")
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.LichSuChat", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuChats")
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.SanPickleball", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("SanPickleballs")
                        .HasForeignKey("ChiNhanhID");

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.ThanhToan", b =>
                {
                    b.HasOne("Pickleball_Smart.Models.DonDatSan", "DonDatSan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("DonDatSanID");

                    b.Navigation("DonDatSan");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.ChiNhanh", b =>
                {
                    b.Navigation("SanPickleballs");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DichVuPhuTro", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.DonDatSan", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");

                    b.Navigation("GhepCapAIs");

                    b.Navigation("LichSuChats");
                });

            modelBuilder.Entity("Pickleball_Smart.Models.SanPickleball", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDatSans");
                });
#pragma warning restore 612, 618
        }
    }
}
